### ISSUE TITLE
need a way to identify - in Slack - people that are stuck in onboarding flow

### ISSUE THREAD

**Issue by karamassie** [hackclub/toriel#201]
If new users are still a guest after , say 6 hours, #welcome-committee should get an alert 

The design should look like this IMO:
if user starts onboarding toriel flow (that is, has accepted the email invite and created a username) and 
if 6 hours has passed and they're not a full member 
then alert (something like "kara has not completed (step name)" or "kara has been onboarding for 6 hours" or whatever works!)

there might be a better or easier way to signify being 'stuck' and I'm open to any solutions!

**Comment by karamassie** [comment]
once this is done, please add to our flow design doc too

**Comment by VelocityDesign** [comment]
I'm thinking we can use [this API method](https://api.slack.com/methods/users.lookupByEmail) to look up a user (since we don't have their Slack User IDs stored), get their User IDs, and check if they're a guest.

Since we're looking at users who are still a guest, perhaps we should make a new 'isGuest' column on AirTable. Then, we can filter for users who are still guests. The other option is we can check for all invited users in the past X hours who are still guests, and then have Toriel bring it up.

Another aspect to think about is, do we want these follow-ups to become SLAcker tickets? If not, how do we restrict these from becoming tickets? Do we want to have these as a top-level message or as a reply?

**Comment by tregsthedev** [comment]
We do store user IDs!

**Comment by VelocityDesign** [comment]
Oh, okay! Does Prisma store the invite date, or is that just in the Airtable?

**Comment by ShubhamPatilsd** [comment]
Should be fixed in the latest commit: https://github.com/hackclub/toriel/commit/d00799b97b6bd760b75f30df5bbab4ba1de24973

I didn't realize I had push access to the main branch, so if we want to review the code I can push them separately into a PR.

I did change the database here, includes an `enum` type for internal state logging of the user in the onboarding flow, as well as a field in the Invite table to track the id of a scheduled message (this message is scheduled for 6 hours into the future saying "XYZ is stuck" and is cancelled when user finishes the flow)

**Comment by karamassie** [comment]
working fantastically!
